public class Prepositions {
	public static void main(String args[]){
		String I="انا";
		String About="كن";
		String Above="فوق";
		String Across="مبل";
		String After="لبر";
		String Against="صر";
		String Among="لبينا";
		String Around="حول";
		String As="من";
		String At="كن";
		String Before="قنل";
		String Behind="جلض";
		String Below="أدنا";
		String Beneath="جحانبا";
		String Beside="بجالب";
		String Between="بين";
		String Down="أسفر";
		String During="أثنا";
		String For="من";
		String From="هن";
		String In="مف";
		String Inside="راخل";
		String On="كن";
		String To="إلي";
		String Till="حا";
		String Until="";
		String Under="لحت";
		String With="مع";
		String Because="بسبب";
		String toLeave="ترك";
		String toReserve="حجز";
		String toMove="حرك";
		String toCarry="حمل";
		String toStudy="درس";
		String toGo="ذهب";
		String toFollow="تبع";
		String toGather="جمع";
		String toBurn="حرق";
		String toSave="حفظ";
		String toComeIn="دخل";
		String toMention="ذكر";
		String toSearch="بحث";
		String toSit="جلس";
		String toHappen="حدث";
		String toAttend="حضر";
		String toGoOut="خرج";
		String toPush="دفع";
		String toReturn="رجغ";
		String toRide="ركب";
		String toSteal="سرق";
		String toHear="سمع";
		String toMake="صنع";
		String toCook="طبف";
		String toKnow="عسل";
		String toWash="غسل";
		String toUnderstand="فهم";
		String toJump="قفز";
		String toHate="كره";
		String toPlay="لعب";
		String toGoDown="نزل";
		String toEscape="هرب";
		String Small="صخر";
		String Big="كبي";
		String Short="قمي";
		String Tall="طوير";
		String Smart="زكي";
		String Stupid="كبي";
		String Rich="تري";
		String Poor="فغير";
		String Old="فدني";
		String New="جربرع";
		String Pretty="خمنل";
		String Ugly="فبح";
		String Clean="قنز";
		String Dirty="كاي";
		String Expensive="ثمبن";
		String Cheap="";
		String Good="جبر";
		String Bad="نني";
		String Easy="سمل";
		String Difficult="صكن";
		String Heavy="نمو";
		String Fat="بربن";
		String Thin="رض";
		String Fast="ستع";
		String Slow="لطيء";
		String Balloon="بالون";
		String The="ال";
		String House="بيت";
		String Lion="أسد";
		String Car="ركب";
		String Book="قرا";
		//System.out.println(I+" "+toMove+" "+Fast+" "+Across+" "+The+House);
		//System.out.println("I move fast across the house.");
		//System.out.println(I+" "+toBurn+" "+Old+" "+The+Balloon);
		//System.out.println("I burn the old balloon.");
		//System.out.println(I+" "+toFollow+" "+The+Lion);
		//System.out.println("I follow the lion.");
		//System.out.println(I+" "+toEscape+" "+The+Lion);
		//System.out.println("I escape the lion.");
		//System.out.println(I+" "+toReturn+" "+To+" "+The+Car);
		//System.out.println("I return to the car.");
		//System.out.println(I+" "+toRide+" "+In+" "+The+Car);
		//System.out.println("I ride in the car.");
		//System.out.println(I+" "+toStudy+" "+With+" "+The+Book);
		//System.out.println("I study with the book.");
		String sentence=I+" "+toStudy+" "+With+" "+The+Book;
		//String[] words=new String [5];
		for (int i=0; i<4; i++){
			String words[]=sentence.split(" ");
			if (i==3){
				System.out.print("______ ");
			}
			System.out.print(words[i]+" ");
		}
	}
}
